# Generated by Django 4.0.6 on 2022-08-21 19:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('chat', '0002_keys'),
    ]

    operations = [
        migrations.AlterField(
            model_name='keys',
            name='keys_owner',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='keys', to=settings.AUTH_USER_MODEL),
        ),
    ]
