# Generated by Django 4.0.6 on 2022-08-21 19:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0003_alter_keys_keys_owner'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Keys',
        ),
    ]
