# Generated by Django 4.0.7 on 2022-09-15 06:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0004_delete_keys'),
    ]

    operations = [
        migrations.AddField(
            model_name='privatechatmessage',
            name='is_read',
            field=models.BooleanField(default=False),
        ),
    ]
