# Generated by Django 4.0.6 on 2022-07-26 15:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import user_profile.models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('modified_on', models.DateTimeField(auto_now=True)),
                ('first_name', models.CharField(max_length=50, null=True)),
                ('last_name', models.CharField(max_length=50, null=True)),
                ('bio', models.TextField(default='', max_length=100)),
                ('date_of_birth', models.DateField(null=True)),
                ('address', models.CharField(max_length=100, null=True)),
                ('phone', models.CharField(max_length=10, null=True)),
                ('gender', models.CharField(choices=[('MALE', 'Male'), ('FEMALE', 'Female'), ('OTHER', 'Other')], default='MALE', max_length=6)),
                ('looking_for', models.CharField(choices=[('MALE', 'Male'), ('FEMALE', 'Female'), ('BOTH', 'Both')], default='BOTH', max_length=6)),
                ('profile_picture', models.ImageField(null=True, upload_to=user_profile.models.path_and_rename)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Heart',
            fields=[
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('modified_on', models.DateTimeField(auto_now=True)),
                ('received_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='heart_receiver', to='user_profile.userprofile')),
                ('sent_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='heart_sender', to='user_profile.userprofile')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
