# Generated by Django 4.0.6 on 2022-07-31 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0002_userprofile_lat_userprofile_long'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='body_type',
            field=models.CharField(choices=[('THIN', 'Thin'), ('AVERAGE', 'Average'), ('FIT', 'Fit'), ('MUSCULAR', 'Muscular'), ('A LITTLE EXTRA', 'A Little Extra'), ('CURVY', 'Curvy')], default='AVERAGE', max_length=15),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='education',
            field=models.CharField(choices=[('HIGH SCHOOL', 'High School'), ('COLLEGE', 'College'), ('BACHELORS DEGREE', 'Bachelors Degree'), ('MASTERS', 'Masters'), ('PHD / POST DOCTORAL', 'PhD / Post Doctoral')], default='HIGH SCHOOL', max_length=100),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='eye_color',
            field=models.CharField(choices=[('BLACK', 'black'), ('BROWN', 'brown'), ('BLUE', 'blue'), ('GREEN', 'green'), ('HAZEL', 'hazel'), ('OTHER', 'other')], default='BLACK', max_length=10),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='hair_colour',
            field=models.CharField(choices=[('BLACK', 'Black'), ('BLONDE', 'Blonde'), ('BROWN', 'Brown'), ('RED', 'Red'), ('GREY', 'Grey'), ('BALD', 'Bald'), ('BLUE', 'Blue'), ('PINK', 'Pink'), ('GREEN', 'Green'), ('PURPLE', 'Purple'), ('OTHER', 'Other')], default='BLACK', max_length=10),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='hair_length',
            field=models.CharField(choices=[('LONG', 'Long'), ('SHOULDER LENGTH', 'Shoulder Length'), ('AVERAGE', 'Average'), ('SHORT', 'Short'), ('SHAVED', 'Shaved')], default='LONG', max_length=100),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='relationship_status',
            field=models.CharField(choices=[('SINGLE', 'single'), ('WIDOWED', 'Widowed'), ('SEPARATED', 'Separated')], default='SINGLE', max_length=100),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='religion',
            field=models.CharField(choices=[('HINDU', 'hindu'), ('CHRISTIAN', 'christian'), ('MUSLIM', 'muslim'), ('BUDDHIST', 'buddhist'), ('OTHER', 'other')], default='HINDU', max_length=100),
        ),
    ]
