# Generated by Django 4.0.6 on 2022-08-07 07:21

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0007_userprofile_zodiac'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='zodiac',
            field=models.CharField(blank=True, choices=[('Aquarius', 'Aquarius'), ('Pisces', 'Pisces'), ('Aries', 'Aries'), ('Taurus', 'Taurus'), ('Gemini', 'Gemini'), ('Cancer', 'Cancer'), ('Leo', 'Leo'), ('Virgo', 'Virgo'), ('Libra', 'Libra'), ('Scorpio', 'Scorpio'), ('Sagittarius', 'Sagittarius'), ('Capricorn', 'Capricorn')], max_length=15, null=True),
        ),
        migrations.CreateModel(
            name='UserInterest',
            fields=[
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('modified_on', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(blank=True, max_length=20, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interest', to='user_profile.userprofile')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
