# Generated by Django 4.0.6 on 2022-08-15 11:01

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0008_alter_userprofile_zodiac_userinterest'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserConnection',
            fields=[
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('modified_on', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='connections', to='user_profile.userprofile')),
                ('user', models.ManyToManyField(null=True, to='user_profile.userprofile')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
