# Generated by Django 4.0.6 on 2022-08-15 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0009_userconnection'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userconnection',
            name='user',
            field=models.ManyToManyField(to='user_profile.userprofile'),
        ),
    ]
