# Generated by Django 4.0.7 on 2022-09-17 14:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0013_remove_key_second_private_key'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userconnection',
            old_name='user',
            new_name='connections',
        ),
    ]
