# Generated by Django 4.0.7 on 2022-09-20 19:34

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0015_alter_userconnection_owner'),
    ]

    operations = [
        migrations.CreateModel(
            name='BlockedUser',
            fields=[
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('modified_on', models.DateTimeField(auto_now=True)),
                ('owner', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='blocked_users', to='user_profile.userprofile')),
                ('users', models.ManyToManyField(to='user_profile.userprofile')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
